django_gunicorn/django_gunicorn/album/urls.py
from django.conf.urls import url
from django_gunicorn.album import views

app_name='album'
urlpatterns =[

	url(r'^add/',views.addAlbum,name='addAlbum'),
	url(r'^details/(?P<album_id>[0-9]+)$',views.details,name='details'),
	url(r'^details/(?P<album_id>[0-9]+)/remove_album$',views.remove_album,name='remove_album'),
	url(r'^album/(?P<album_id>[0-9]+)/add/song/',views.add_song,name="add_song"),
	url(r'^album/(?P<album_id>[0-9]+)/remove_song/(?P<song_id>[0-9]+)$',views.remove_song,name='remove_song'),
	#url(r'^details/(?P<album_id>[0-9]+)/edit_album$',views.edit_album,name='edit_album'),
]

django_gunicorn/django_gunicorn/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django_gunicorn.album import views as album_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',album_views.index,name='index'),
    url(r'^album/',include('django_gunicorn.album.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django_gunicorn/django_gunicorn/album/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Album(models.Model):
	user=models.ForeignKey(User,default='admin', on_delete=models.CASCADE)
	logo=models.FileField()
	title=models.CharField(max_length=50,default=" ")
	artist=models.CharField(max_length=100,default=" ")
	genre=models.CharField(max_length=30,default=" ")
	details=models.TextField(max_length=200,default=" ")

	def __str__(self):
		return str(self.title)
class Song(models.Model):
	album=models.ForeignKey(Album,on_delete=models.CASCADE)
	song_title=models.CharField(max_length=30)
	file=models.FileField(default='')

	def __str__(self):
		return str(self.song_title)

django_gunicorn/django_gunicorn/album/forms.py
from django import forms
from django_gunicorn.album.models import Album,Song

class AlbumForm(forms.ModelForm):
	class Meta:
		model=Album
		fields=['logo','title','artist','genre','details']
class SongForm(forms.ModelForm):
	class Meta:
		model=Song
		fields=['song_title','file']

django_gunicorn/django_gunicorn/album/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate
from django_gunicorn.album.models import Album,Song
from django_gunicorn.album.forms import AlbumForm,SongForm



def index(request):
	if request.user.is_authenticated:
		albums=Album.objects.filter(user=request.user)
		return render(request,'album/index.html',{'albums':albums})
	else:
		return render(request,'album/main.html')

def addAlbum(request):
	if request.user.is_authenticated:
		if request.method=="POST":
			form=AlbumForm(request.POST,request.FILES)
			if form.is_valid():
				post=form.save(commit=False)
				post.user=request.user
				post.save()
				return redirect("/")
		else:
			form=AlbumForm()
		return render(request,'album/create.html',{'form':form})
def details(request,album_id):
	if request.user.is_authenticated:
		detailObject=Album.objects.get(pk=album_id)
		songObject=Song.objects.filter(album=detailObject)
		return render(request,'album/details.html',{'detailObject':detailObject,'songObject':songObject})

def remove_album(request,album_id):
	if request.user.is_authenticated:
		if request.method=="POST":
			deleteObject=Album.objects.get(pk=album_id)
			deleteObject.delete()
			return redirect("/")
	else:
		return render(request,'album/main.html')
#def edit(request,album_id):

def add_song(request,album_id):
	if request.user.is_authenticated:
		detailObject=get_object_or_404(Album,pk=album_id)
		if request.method=="POST":
			form=SongForm(request.POST,request.FILES)
			if form.is_valid():
				post=form.save(commit=False)
				post.album=Album.objects.get(pk=album_id)
				post.save()
				return redirect('/')
		else:
			form=SongForm()
		return render(request,'album/song.html',{'form':form})
def remove_song(request,album_id,song_id):
	if request.user.is_authenticated:
		if request.method=='POST':
			detailObject=get_object_or_404(Album,pk=album_id)
			deleteObject=Song.objects.get(pk=song_id)
			deleteObject.delete()
			return render(request,'album/details.html',{'detailObject':detailObject})
	else:
		return render(request,'album/main.html')

django_gunicorn/django_gunicorn/album/templates/album/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Create Albums and store songs in it on cloud!</title>

    <!-- Bootstrap Core CSS -->

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Concert+One|Lobster" rel="stylesheet">
    <!-- Plugin CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'album/vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'album/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'album/css/custom.css' %}">
    
    <!-- Theme CSS -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">Sara</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <form action="/accounts/logout/" method="POST">
                        {%csrf_token%}
                       <button type="submit" class="btn btn-outline">Logout</button>
                        </form>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{%block body%}

{%endblock%}
 

<script type="text/javascript" src="{% static 'album/vendors/jquery/dist/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'album/js/main.js' %}"></script>
<script type="text/javascript" src="{% static 'album/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>

</body>
</html>

django_gunicorn/django_gunicorn/album/templates/album/create.html
{%extends 'album/base.html'%}

{%block body%}



<div class="container">
<div class="row row-content">
<form action="" method="POST" enctype="multipart/form-data" class="col-md-offset-3 col-md-6">
{% csrf_token %}
 <div class="form-group">
    <label for="exampleInputFile">Logo</label>
    <div class="fileUpload btn btn-outline-2">
    <span>Upload Here</span>
    <input type="file" class="upload"  name="logo" required id="id_logo"/>
</div>
 </div>
<div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <input type="text" class="form-control" name="title" value=" " required id="id_title" maxlength="50" placeholder="Title">
</div>
<div class="form-group">
    <label for="exampleInputEmail1">Artist</label>
    <input type="text" class="form-control"  name="artist" value=" " required id="id_artist" maxlength="100"  placeholder="Artist">
</div>
<div class="form-group">
    <label for="exampleInputEmail1">Genre</label>
    <input type="text" class="form-control"  name="genre" value=" " required id="id_genre" maxlength="30" placeholder="Genre">
</div>
<div class="form-group">
    <label for="exampleInputEmail1">Details</label>
    <textarea class="form-control" name="details" required cols="40" id="id_details" maxlength="200" rows="10" rows="3"></textarea>
</div>
<button type="submit" class="btn btn-default">Submit</button>
<p style="padding-top: 10px;"></p>
</form>
</div>
</div>
{%endblock%}


 

django_gunicorn/django_gunicorn/album/templates/album/details.html
{% extends 'album/base.html' %}
{% block body%}


<div class="container">
    <div class="row profile">
  
  </div>
</div>
<div class="container">
<div class="row-content profile">
  <div class="col-md-3">
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
          <img src="{{detailObject.logo.url}}" class="img-responsive" alt="">
        </div>
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            {{detailObject.title}}
          </div>
          <div class="profile-usertitle-job">
            {{detailObject.genre}}
          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        <div class="profile-userbuttons">
         <form action="{% url 'album:remove_album' detailObject.id%}" method="POST">
			{%csrf_token%}
			<input type="submit" value="delete" class="btn btn-outline-3 btn-sm">
			</form> 
        </div>
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
  
        <!-- END MENU -->
      </div>
    </div>
    <div class="col-md-9">
            <div class="profile-content">
				<h5 class="text-center"><a data-toggle="modal" data-target="#myModal" class="btn btn-outline-2 btn-xl page-scroll">Add Songs Now!</a></h5>



			<div class="row">
			{% for item in detailObject.song_set.all%}
				<div class="panel panel-default">
					  <div class="panel-body">
					    <div class="col-md-4">
					    	<h4 class="text-center">{{item.song_title}}</h4>
					    </div>
					    <div class="col-md-offset-4 col-md-2">
		
            <a href="{{item.file.url}}" value="play" class="btn btn-outline-2"><span class="glyphicon glyphicon-play"></span> Play</a>
          
          </div>
           <div class="col-md-2">
					    	<form action="{%url 'album:remove_song' detailObject.id item.id %}" method="POST" class="col-xs-12">
                {%csrf_token%}
                <button type="submit" value="delete" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Trash</button>
              </form>
					    </div>
					  </div>
				</div>
			{%endfor%}
			</div>



            </div>


    </div>
</div>
</div>

<div class="modal fade" id="myModal" tabindex="-3" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Song</h4>
      </div>
      <div class="modal-body">
        <form action="{% url 'album:add_song' detailObject.id %}" method="POST" enctype="multipart/form-data">
        	{%csrf_token%}
     <div class="form-group">   	
    <input type="file" name="file" required id="id_file"  class="file">
    <div class="input-group col-xs-12">
      <span class="input-group-addon"><i class="glyphicon glyphicon-music"></i></span>
      <input type="text" class="form-control input-lg" disabled placeholder="Upload Image">
      <span class="input-group-btn">
        <button class="browse btn btn-primary input-lg" type="button"><i class="glyphicon glyphicon-search"></i> Browse</button>
      </span>
    </div>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <input type="text" class="form-control" name="song_title" required maxlength="30" id="id_song_title" placeholder="Title">
</div>
 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save </button>
         </form>
      </div>
    </div>
  </div>
</div>


{%endblock%}
<!--
<img src="{{detailObject.logo.url}}" >
<h1>{{detailObject.title}}</h1>
<h2>{{detailObject.artist}}</h2>
<h3>{{detailObject.genre}}</h3>
<ul>
	{% for item in detailObject.song_set.all%}
	<li><audio controls><source src="{{item.file.url}}" type="audio/mp3"></audio>{{item.song_title}}</li>
	<form action="{%url 'album:remove_song' detailObject.id item.id %}" method="POST">
		{%csrf_token%}
		<input type="submit" value="X">
	</form>
	{%endfor%}
</ul>
<form action="{% url 'album:remove_album' detailObject.id%}" method="POST">
	{%csrf_token%}
	<input type="submit" value="delete">
</form>
<a href="{% url 'album:add_song' detailObject.id %}">Add song</a>-->

django_gunicorn/django_gunicorn/album/templates/album/index.html
{%extends 'album/base.html' %}
{%block body%}

<div class="container">
	<div class="row row-content">
		<div class="col-md-offset-3 col-md-6">
			<blockquote> 
				<h4 class="text-center">Create Albums And Store Your Favourite Songs In It</h4>
				<h5 class="text-center"><a href="{% url 'album:addAlbum' %}" class="btn btn-outline-2 btn-xl page-scroll">Add Albums Now!</a></h5>
			</blockquote>
		</div>
	</div>
	<div class="row row-content">
	{% for album in albums %}
		<div class="col-xs-12 col-md-4">
			<div class="thumbnail">
		      <img src="{{album.logo.url}}" class="img">
		      <div class="caption">
		        <h1 class="text-center"><small class="t1">{{album.title}}</small></h1>
		        <p><h4 class="text-center"><small class="t1">{{album.details}}</small></h4></p>
		        <h4 class="text-center"><a href="{%url 'album:details' album.id %}" class="btn btn-outline" role="button">View Album</a> 
		      </div>
		    </div>	
		</div>
		{%endfor%}
	</div>

</div>
<!--{% for album in albums %}
<a href="{%url 'album:details' album.id %}">{{album.title}}</a><br>
{%endfor%}-->


{%endblock%}

django_gunicorn/django_gunicorn/album/templates/album/main.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Create Albums and store songs in it on cloud!</title>

    <!-- Bootstrap Core CSS -->

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Concert+One|Lobster" rel="stylesheet">
    <!-- Plugin CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'album/vendors/bootstrap/dist/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'album/vendors/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static  'album/css/login-register.css' %}">
	 <link rel="stylesheet" type="text/css" href="{% static  'album/css/custom.css' %}">
     <link rel="stylesheet" href="{% static 'album/simple-line-icons/css/simple-line-icons.css' %}">
    <!-- Theme CSS -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">Sara</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a data-toggle="modal" href="javascript:void(0)" onclick="openLoginModal();">Login</a>
                    </li>
                    <li>
                        <a data-toggle="modal" href="javascript:void(0)" onclick="openRegisterModal();">Signup</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-sm-7">
                    <div class="header-content">
                        <div class="header-content-inner">
                            <h1>Sara Provides you cloud storage to store songs in your albums!</h1>
                            <a data-toggle="modal" href="javascript:void(0)" onclick="openRegisterModal();" class="btn btn-outline btn-xl page-scroll">Start Now for Free!</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="device-container">
                        <div class="device-mockup macbook_2015 grey">
                            <div class="device">
                                <div class="screen">
                                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                    <!--<img src="img/bg-2.jpg" class="img-responsive" alt="">-->
                                </div>
                                <div class="button">
                                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </header>
<div class="modal fade login" id="loginModal">
          <div class="modal-dialog login animated">
              <div class="modal-content">
                 <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Login with</h4>
                    </div>
                    <div class="modal-body">  
                        <div class="box">
                             <div class="content">
                                <div class="social">
                                    <a class="circle github" href="/accounts/github/login/">
                                        <i class="fa fa-github fa-fw"></i>
                                    </a>
                                    <a id="google_login" class="circle google" href="/accounts/google/login/">
                                        <i class="fa fa-google-plus fa-fw"></i>
                                    </a>
                                    <a id="facebook_login" class="circle facebook" href="/accounts/facebook/login/">
                                        <i class="fa fa-facebook fa-fw"></i>
                                    </a>
                                </div>
                                <div class="division">
                                    <div class="line l"></div>
                                      <span>or</span>
                                    <div class="line r"></div>
                                </div>
                                <div class="error"></div>
                                <div class="form loginBox">
                                    <form method="POST" action="/accounts/login/">
                                    {%csrf_token%}
                                    <input id="id_login" class="form-control" type="text" placeholder="Email" name="login">
                                    <input id="id_password" class="form-control" type="password" placeholder="Password" name="password">
                                    <input class="btn btn-default btn-login" type="submit" value="Login">
                                    </form>
                                </div>
                             </div>
                        </div>
                        <div class="box">
                            <div class="content registerBox" style="display:none;">
                             <div class="form">
                                <form method="POST" action="/accounts/signup/">
                                {%csrf_token%}
                                <input id="id_username" class="form-control" type="text" placeholder="Username" name="username">
                                <input id="id_password1" class="form-control" type="password" placeholder="Password" name="password1">
                                <input id="id_password2" class="form-control" type="password" placeholder="Repeat Password" name="password2">
                                <input class="btn btn-default btn-register" type="submit" value="Create account" name="commit">
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="forgot login-footer">
                            <span>Looking to 
                                 <a href="javascript: showRegisterForm();">create an account</a>
                            ?</span>
                        </div>
                        <div class="forgot register-footer" style="display:none">
                             <span>Already have an account?</span>
                             <a href="javascript: showLoginForm();">Login</a>
                        </div>
                    </div>        
              </div>
          </div>
      </div>
<section id="features" class="features">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-heading">
                        <h2>Our Features</h2>
                        <p class="text-muted">Check out what you can do with project!</p>
                        <hr>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-4 foo-1">
                                <div class="feature-item">
                                   <i class="fa fa-music" aria-hidden="true"></i>
                                    <h3>Unlimited Music</h3>
                                    <p class="text-muted">Upload Your Favourite music,and listen it anywhere!</p>
                                </div>
                            </div>
                            <div class="col-md-4 foo-2">
                                <div class="feature-item">
                                    <i class="fa fa-play" aria-hidden="true"></i>
                                    <h3>Play Online</h3>
                                    <p class="text-muted">Listen Your Favourite song online!</p>
                                </div>
                            </div>
                               <div class="col-md-4 foo-3">
                                <div class="feature-item">
                                   <i class="fa fa-bullhorn" aria-hidden="true"></i>
                                    <h3>Share</h3>
                                    <p class="text-muted">Share with everyone on the cloud!</p>
                                </div>
                            </div>
                        </div>
                  
                    </div>
                </div>
            </div>
        </div>
    </section>


 <footer>
        <div class="container">
            <div class="row">
            <p>&copy; 2017 Sara. All Rights Reserved.</p>
            <!--<ul class="list-inline">
                <li>
                    <a href="#">Privacy</a>
                </li>
                <li>
                    <a href="#">Terms</a>
                </li>
                <li>
                    <a href="#">FAQ</a>
                </li>
            </ul>-->
        </div>
        </div>
    </footer>


<script type="text/javascript" src="{% static 'album/vendors/jquery/dist/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'album/js/main.js' %}"></script>
<script type="text/javascript" src="{% static 'album/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'album/js/login-register.js' %}"></script>
<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
<script src="{%static 'album/js/custom.js'%}" type='text/javascript'></script>